steps:
  # Construir la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/seqia:$COMMIT_SHA', '-t', 'gcr.io/$PROJECT_ID/seqia:latest', '.']
  
  # Hacer push de la imagen al Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'gcr.io/$PROJECT_ID/seqia']
  
  # Desplegar a Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'seqia-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/seqia:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'

# Timeout para el build (máximo 20 minutos)
timeout: 1200s

# Opciones adicionales
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

images:
  - 'gcr.io/$PROJECT_ID/seqia:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/seqia:latest'
